model:
    model_str: MiT_B_2

fid:
    device_batch_size: 80
    num_samples: 50000
    
    cache_ref: "/kmh-nfs-ssd-us-mount/data/latents/gzy_vae_cached_imagenet_dist/imagenet_256_fid_stats.npz"

sampling:
    # CFG scale and interval recommended for provided iMF-B/2 checkpoint
    # You can add more omega and intervals to do a grid search
    num_steps: 1
    interval:
        - [0.4, 0.65]
    omegas: [7.5, 8.0, 8.5, 9.0]

logging:
    wandb_project: 'km_DiT_latent' # change to your wandb project
    wandb_entity: 'zhh24-massachusetts-institute-of-technology' # paste your wandb entity here
    wandb_tags: # use your own tags
        - lyy
    wandb_notes: 'eval release v14 B' # your wandb notes

load_from: gs://kmh-gcp-us-central1/qiao_zhicheng_hanhong_files/Meanflow/20251208_184429_pws2ug_kmh-tpuvm-v6e-64-spot-101_us-central1-b__b_lr_ep_eval/checkpoint_800640 # path to load checkpoint
eval_only: True # set to True for evaluation only